#!/bin/sh

TEST_DIRS='t xt'

while [ "$#" -gt "0" ]; do
  case $1 in
    --cover)
      cover -delete -silent
      export HARNESS_PERL_SWITCHES='-MDevel::Cover=-ignore,^x?t/,-blib,0'
      ;;
    *)
      echo "Invalid option: $1"
      exit 1
      ;;
    esac
  shift
done

if [ -n "$AUTHOR_TESTING" ] && [ "$AUTHOR_TESTING" -eq 0 ]; then
  TEST_DIRS='t'
fi

prove -l $TEST_DIRS && MOO_XS_DISABLE=1 prove -l $TEST_DIRS
