#!/bin/bash

DEPS=''
for arg; do
  case $arg in
    --deps)
      DEVELOP=''
      if [ -z "$AUTHOR_TESTING" ] || [ "$AUTHOR_TESTING" -ne 0 ]; then
        DEVELOP='--with-develop'
      fi
      DEPS="$DEPS $(cpanm --showdeps -q . --with-recommends --with-suggests $DEVELOP)"
    ;;
    *)
      DEPS="$DEPS $arg"
    ;;
  esac
done

for dep in $DEPS; do
  case $dep in
    perl*) ;;
    *)
      printf "Installing (without testing) $dep ..."
      (
        while true; do
          sleep 1
          printf '.'
        done
      ) &
      PROG=$!
      OUT=$(cpanm --verbose --no-interactive --no-man-pages --notest $dep 2>&1 )
      STATUS=$?
      kill $PROG
      wait $PROG 2>/dev/null
      if [ $STATUS != 0 ]; then
        echo ' Failed!'
        echo "$OUT"
        exit $?
      fi
      echo ' Done'
    ;;
  esac
done
